# x="CTTCGAAAGTTTGGGCCGAGTCTTACAGTCGGTCTTGAAGCAAAGTAACGAACTCCACGGCCCTGACTACCGAACCAGTTGTGAGTACTCAACTGGGTGAGAGTGCAGTCCCTATTGAGTTTCCGAGACTCACCGGGATTTTCGATCCAGCCTCAGTCCAGTCTTGTGGCCAACTCACCAAATGACGTTGGAATATCCCTGTCTAGCTCACGCAGTACTTAGTAAGAGGTCGCTGCAGCGGGGCAAGGAGATCGGAAAATGTGCTCTATATGCGACTAAAGCTCCTAACTTACACGTAGACTTGCCCGTGTTAAAAACTCGGCTCACATGCTGTCTGCGGCTGGCTGTATACAGTATCTA"
y = "CTTCGAAAGTTTGGGCCGAGTCTTACAGT"
# m=[AA,AT,AG,AC,TG,TC,TA,TT,GA,GT,GC,GG,CA,CT,CG,CC]
m = ['GC', 'TT']



for i in m:
    count = 0
    for x in range(len(y)-1):
         if y[x] + y[x + 1] == i:
            count += 1
    print(i, count)

l = []

s = 'ATCG'

for a in s:
    n1 = a
    for b in s:
        n2 = n1 + b
        for c in s:
            n3 = n2 + c
            for d in s:
                l.append(n3+d)
print(l)
